// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orgmkudrmldirywakhhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yZ21rdWRybWxkaXJ5d2FraGhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MzA2MzMsImV4cCI6MjA3MzUwNjYzM30.2e0reAj5sYSewFhXF2CoeZLzdUtA981KYT9hDUil0gc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});